apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  strategy: {}
  template:
    metadata:
      labels:
        app: go-app
    spec:
    initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z host.minikube.internal 5432; do echo waiting for db; sleep 2; done']
    containers:
      - image: my-go-app:v1
        name: my-go-app
        imagePullPolicy: Never 
        resources: {}
status: {}
