name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      # I haven't written any tests yet, so this is commented out for now. I'll add it back in once I have some tests to run.
      # - name: Run tests
      #   run: go test ./...

      - name: Run linter
        uses: golangci/golangci-lint-action@v7
        with:
            version: v2.11.3

      - name: Build project
        run: go build ./...
